### ISSUE TITLE
Verify is CCM is created for a ConfigMap which is not used in any deployment

### ISSUE THREAD

**Issue by surendar-b** [gopaddle-io/configurator#86]
**Describe the bug**
     If the cluster has ConfigMap that is not used by any of the deployment at that point the configurator is creating a version for the ConfigMap that needs to  be verified.
**To Reproduce**
1.Create a ConfigMap in cluster
```sh
    $ kubectl apply -f demo-config.yaml
```
```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
        name: demo-config
    data:
      # property-like keys; each key maps to a simple value
      player_initial_lives: "3"
      ui_properties_file_name: "user-interface.properties"
      # file-like keys
      game.properties: |
        android.apk=free fire,bgmi
        computer=stambled guys    
      user-interface.properties: |
        color.good=purple
        color.bad=yellow
```
2.Create deployment with ConfigMap mounted. (Node:- except 'demo-config' use some other CM)
```sh
$ kubectl apply -f deployment.yaml
```
3.Install configurator 
4.Verify annotation added in 'spec.template.metadata.annotation' level in deployment.
```sh
$ kubectl get deployment <deploymentname> -o yaml
```
5.Verify the ConfigMap version is created for the deployment using ConfigMap. 
```$ kubectl get ccm```

6.Verify the new version created for the 'demo-config'.
```sh
       $ kubectl get ccm
```
**Expected behavior**
    In  step 6 configurator must create a new version for unused ConfigMap
